apiVersion: v1
kind: Secret
metadata:
  name: justapi-db
  labels:
    {{- include "justapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.secrets.db.url | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: justapi-redis
  labels:
    {{- include "justapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.secrets.redis.url | quote }}
