"""Type stubs for the compiled justapi._justapi extension (auto-generated from runtime introspection)."""
from _typeshed import Incomplete
from typing import Any, Optional, Iterator, Mapping, List, Dict

def serve(addr: str) -> None: ...

class BackgroundTasks:
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_task(self, func: Any, *args: Any, **kwargs: Any) -> Any: ...
    def run(self, ) -> Any: ...
    def shutdown(self, wait: Any) -> Any: ...
    def stats(self, ) -> Any: ...
    def task_count(self, ) -> Any: ...

class Dag:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def execute(self, inputs: Any) -> Any: ...

class DagNode:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Database:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def max_connections(self) -> Any: ...
    @property
    def url(self) -> Any: ...

class HTTPConnection:
    def __contains__(self, key: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __setitem__(self, key: Any, value: Any) -> Any: ...
    @property
    def app(self) -> Any: ...
    @property
    def auth(self) -> Any: ...
    @property
    def base_url(self) -> Any: ...
    @property
    def client(self) -> Any: ...
    @property
    def cookies(self) -> Any: ...
    def get(self, key: Any, default: Any = ...) -> Any: ...
    @property
    def headers(self) -> Any: ...
    @property
    def http_version(self) -> Any: ...
    @property
    def method(self) -> Any: ...
    @property
    def path(self) -> Any: ...
    @property
    def path_params(self) -> Any: ...
    @property
    def query_params(self) -> Any: ...
    @property
    def query_string(self) -> Any: ...
    def receive(self, ) -> Any: ...
    @property
    def scheme(self) -> Any: ...
    @property
    def scope(self) -> Any: ...
    @property
    def session(self) -> Any: ...
    @property
    def state(self) -> Any: ...
    @property
    def url(self) -> Any: ...
    def url_for(self, name: Any, **kwargs: Any) -> Any: ...
    @property
    def user(self) -> Any: ...

class Headers:
    def __contains__(self, key: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: Any, default: Any = ...) -> Any: ...
    def items(self, ) -> Any: ...
    def keys(self, ) -> Any: ...
    def mutable(self, ) -> Any: ...
    @property
    def raw(self) -> Any: ...
    def values(self, ) -> Any: ...

class JustAPITestClient:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, path: Any) -> Any: ...
    def get(self, path: Any) -> Any: ...
    def post(self, path: Any, body: Any) -> Any: ...
    def post_with(self, path: Any, body: Any, headers: Any) -> Any: ...
    def put(self, path: Any, body: Any) -> Any: ...

class QueryParams:
    def __contains__(self, key: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: Any, default: Any = ...) -> Any: ...
    def getlist(self, key: Any) -> Any: ...
    def items(self, ) -> Any: ...
    def keys(self, ) -> Any: ...
    def multi_items(self, ) -> Any: ...
    def mutable(self, ) -> Any: ...
    def values(self, ) -> Any: ...

class RateLimitResult:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def allowed(self) -> Any: ...
    @property
    def retry_after_ms(self) -> Any: ...

class RateLimiter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def check_limit(self, key: Any, capacity: Any, replenish_rate: Any, tokens: Any) -> Any: ...
    def new_redis(self, redis_url: Any) -> Any: ...

class Request:
    def __contains__(self, key: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __setitem__(self, key: Any, value: Any) -> Any: ...
    @property
    def app(self) -> Any: ...
    @property
    def auth(self) -> Any: ...
    @property
    def base_url(self) -> Any: ...
    def body(self, ) -> Any: ...
    @property
    def client(self) -> Any: ...
    def close(self, ) -> Any: ...
    @property
    def cookies(self) -> Any: ...
    def form(self, ) -> Any: ...
    def get(self, key: Any, default: Any = ...) -> Any: ...
    @property
    def headers(self) -> Any: ...
    @property
    def http_version(self) -> Any: ...
    def is_disconnected(self, ) -> Any: ...
    def json(self, ) -> Any: ...
    @property
    def method(self) -> Any: ...
    @property
    def path(self) -> Any: ...
    @property
    def path_params(self) -> Any: ...
    @property
    def query_params(self) -> Any: ...
    @property
    def query_string(self) -> Any: ...
    def receive(self, ) -> Any: ...
    @property
    def scheme(self) -> Any: ...
    @property
    def scope(self) -> Any: ...
    def send_push_promise(self, path: Any) -> Any: ...
    @property
    def session(self) -> Any: ...
    @property
    def state(self) -> Any: ...
    def stream(self, ) -> Any: ...
    @property
    def url(self) -> Any: ...
    def url_for(self, name: Any, **kwargs: Any) -> Any: ...
    @property
    def user(self) -> Any: ...

class RequestStream:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class State:
    def __contains__(self, key: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __setitem__(self, key: Any, value: Any) -> Any: ...

class TokenStreamResponse:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class URL:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def fragment(self) -> Any: ...
    @property
    def host(self) -> Any: ...
    @property
    def hostname(self) -> Any: ...
    @property
    def path(self) -> Any: ...
    @property
    def port(self) -> Any: ...
    @property
    def query(self) -> Any: ...
    @property
    def scheme(self) -> Any: ...

class UploadFile:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def close(self, ) -> Any: ...
    @property
    def content_type(self) -> Any: ...
    @property
    def file(self) -> Any: ...
    @property
    def filename(self) -> Any: ...
    @property
    def headers(self) -> Any: ...
    def read(self, size: Any = ...) -> Any: ...
    def seek(self, offset: Any) -> Any: ...
    @property
    def size(self) -> Any: ...
    def write(self, data: Any) -> Any: ...

class WebSocket:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def accept(self, subprotocol: Any = ..., headers: Any = ...) -> Any: ...
    @property
    def app(self) -> Any: ...
    @property
    def application_state(self) -> Any: ...
    @property
    def base_url(self) -> Any: ...
    @property
    def client(self) -> Any: ...
    @property
    def client_state(self) -> Any: ...
    def close(self, code: Any = ..., reason: Any = ...) -> Any: ...
    @property
    def cookies(self) -> Any: ...
    @property
    def headers(self) -> Any: ...
    @property
    def path_params(self) -> Any: ...
    @property
    def query_params(self) -> Any: ...
    def receive(self, ) -> Any: ...
    def receive_bytes(self, ) -> Any: ...
    def receive_json(self, mode: Any = ...) -> Any: ...
    def receive_text(self, ) -> Any: ...
    def send(self, message: Any) -> Any: ...
    def send_bytes(self, message: Any) -> Any: ...
    def send_json(self, data: Any, mode: Any = ...) -> Any: ...
    def send_text(self, message: Any) -> Any: ...
    @property
    def state(self) -> Any: ...
    @property
    def subprotocol(self) -> Any: ...
    @property
    def url(self) -> Any: ...
    def url_for(self, name: Any, **kwargs: Any) -> Any: ...

class WebSocketState:
    @property
    def CONNECTED(self) -> Any: ...
    @property
    def CONNECTING(self) -> Any: ...
    @property
    def DISCONNECTED(self) -> Any: ...
    @property
    def RESPONSE(self) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class _JustAPIApp:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_grpc_service(self, path: Any, handler: Any) -> Any: ...
    def delete(self, path: Any, handler: Any, tags: Any = ..., summary: Any = ..., description: Any = ..., deprecated: Any = ..., status_code: Any = ..., responses: Any = ..., operation_id: Any = ..., openapi_extra: Any = ..., include_in_schema: Any = ..., name: Any = ...) -> Any: ...
    def enable_circuit_breaker(self, failure_threshold: Any, reset_timeout_ms: Any) -> Any: ...
    def enable_gateway(self, path: Any) -> Any: ...
    def enable_request_coalescing(self, headers: Any) -> Any: ...
    def frontend(self, path: Any, directory: Any, fallback: Any = ..., check_dir: Any = ...) -> Any: ...
    def get(self, path: Any, handler: Any, tags: Any = ..., summary: Any = ..., description: Any = ..., deprecated: Any = ..., status_code: Any = ..., responses: Any = ..., operation_id: Any = ..., openapi_extra: Any = ..., include_in_schema: Any = ..., name: Any = ...) -> Any: ...
    def get_database(self, ) -> Any: ...
    def head(self, path: Any, handler: Any, tags: Any = ..., summary: Any = ..., description: Any = ..., deprecated: Any = ..., status_code: Any = ..., responses: Any = ..., operation_id: Any = ..., openapi_extra: Any = ..., include_in_schema: Any = ..., name: Any = ...) -> Any: ...
    def load_wasm_middleware(self, path: Any) -> Any: ...
    def options(self, path: Any, handler: Any, tags: Any = ..., summary: Any = ..., description: Any = ..., deprecated: Any = ..., status_code: Any = ..., responses: Any = ..., operation_id: Any = ..., openapi_extra: Any = ..., include_in_schema: Any = ..., name: Any = ...) -> Any: ...
    def patch(self, path: Any, handler: Any, body_schema: Any = ..., schema: Any = ..., batch_size: Any = ..., batch_window_ms: Any = ..., tags: Any = ..., summary: Any = ..., description: Any = ..., deprecated: Any = ..., status_code: Any = ..., responses: Any = ..., operation_id: Any = ..., openapi_extra: Any = ..., include_in_schema: Any = ..., name: Any = ...) -> Any: ...
    def post(self, path: Any, handler: Any, body_schema: Any = ..., schema: Any = ..., batch_size: Any = ..., batch_window_ms: Any = ..., tags: Any = ..., summary: Any = ..., description: Any = ..., deprecated: Any = ..., status_code: Any = ..., responses: Any = ..., operation_id: Any = ..., openapi_extra: Any = ..., include_in_schema: Any = ..., name: Any = ...) -> Any: ...
    def put(self, path: Any, handler: Any, body_schema: Any = ..., schema: Any = ..., batch_size: Any = ..., batch_window_ms: Any = ..., tags: Any = ..., summary: Any = ..., description: Any = ..., deprecated: Any = ..., status_code: Any = ..., responses: Any = ..., operation_id: Any = ..., openapi_extra: Any = ..., include_in_schema: Any = ..., name: Any = ...) -> Any: ...
    def query(self, path: Any, handler: Any, body_schema: Any = ..., schema: Any = ..., experimental: Any = ..., tags: Any = ..., summary: Any = ..., description: Any = ..., deprecated: Any = ..., status_code: Any = ..., responses: Any = ..., operation_id: Any = ..., openapi_extra: Any = ..., include_in_schema: Any = ..., name: Any = ...) -> Any: ...
    def run(self, addr: Any) -> Any: ...
    def set_database(self, db: Any) -> Any: ...
    def set_grpc_addr(self, addr: Any) -> Any: ...
    def store_meta(self, method: Any, path: Any, body_schema: Any, response_schema_json: Any, tags: Any, summary: Any, description: Any, deprecated: Any, status_code: Any, responses: Any, operation_id: Any, openapi_extra: Any, experimental: Any, include_in_schema: Any) -> Any: ...
    def trace(self, path: Any, handler: Any, tags: Any = ..., summary: Any = ..., description: Any = ..., deprecated: Any = ..., status_code: Any = ..., responses: Any = ..., operation_id: Any = ..., openapi_extra: Any = ..., include_in_schema: Any = ..., name: Any = ...) -> Any: ...
    def url_for(self, name: Any, **kwargs: Any) -> Any: ...
    def use(self, plugin: Any) -> Any: ...
    def websocket(self, path: Any, handler: Any) -> Any: ...

class _StreamSender:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def close(self, ) -> Any: ...
    def send(self, data: Any) -> Any: ...
    def send_error(self, msg: Any) -> Any: ...


class DbPool:
    def query(self, sql: str, params: list | None = ...) -> list: ...
    def execute(self, sql: str, params: list | None = ...) -> int: ...
    def query_async(self, sql: str, params: list | None = ...) -> Any: ...
    def execute_async(self, sql: str, params: list | None = ...) -> Any: ...
    def transaction(self, stmts: list, isolation: str | None = ...) -> Any: ...
