def set_trace_context(trace_id, span_id) -> None: ...
def get_trace_context(): ...
def wrap_result(result): ...
def call_handler(handler, request): ...
def call_batch_handler(handler, requests): ...
def validate_body(schema_fn, body_bytes): ...
def call_plugin_hook(plugin, hook_name) -> None: ...
def run_ws_handler(coro) -> None: ...
