import typing
from ._justapi import TokenStreamResponse as TokenStreamResponse
from _typeshed import Incomplete

class RequestValidationError(Exception):
    errors: Incomplete
    def __init__(self, errors) -> None: ...

class Depends:
    dependency: Incomplete
    use_cache: Incomplete
    def __init__(self, dependency: typing.Callable, use_cache: bool = True) -> None: ...

def adaptive_batch(max_size: int = 32, window_ms: int = 10): ...

class JustAPIApp:
    dependencies: Incomplete
    exception_handlers: Incomplete
    middlewares: Incomplete
    def __init__(self, dependencies: list[Depends] = None) -> None: ...
    def middleware(self, middleware_type: str = 'http'): ...
    def add_exception_handler(self, exc_class, handler) -> None: ...
    def get(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def post(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def put(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def delete(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def patch(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def query(self, path: str, handler=None, body_schema=None, schema=None, experimental: bool = True, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def add_plugin(self, plugin) -> None: ...
    def use(self, plugin) -> None: ...
    def set_database(self, db) -> None: ...
    def enable_gateway(self, config_path: str): ...
    def enable_circuit_breaker(self, failure_threshold: int = 5, reset_timeout_ms: int = 10000): ...
    def enable_request_coalescing(self, headers: list[str] = None): ...
    def set_grpc_addr(self, addr: str): ...
    def add_grpc_service(self, servicer, add_func_to_server) -> None: ...
    def include_controller(self, controller_cls) -> None: ...
    def include_router(self, router, prefix: str = ''): ...
    def run(self, addr: str): ...
    def sse(self, path: str, handler=None): ...
    def websocket(self, path: str, handler=None): ...

class APIRouter:
    prefix: Incomplete
    dependencies: Incomplete
    middlewares: Incomplete
    routes: Incomplete
    def __init__(self, prefix: str = '', dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None) -> None: ...
    def get(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def post(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def put(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def patch(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def delete(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def query(self, path: str, handler=None, body_schema=None, schema=None, experimental: bool = True, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None): ...
    def sse(self, path: str, handler=None, dependencies: list[Depends] = None): ...
    def websocket(self, path: str, handler=None, dependencies: list[Depends] = None): ...

class Controller: ...

def controller(path: str, dependencies: list[Depends] = None): ...
def route_get(path: str, dependencies: list[Depends] | None = None) -> typing.Callable: ...
def route_post(path: str, body_schema=None, schema=None, dependencies: list[Depends] | None = None) -> typing.Callable: ...
def route_put(path: str, body_schema=None, schema=None, dependencies: list[Depends] | None = None) -> typing.Callable: ...
def route_patch(path: str, body_schema=None, schema=None, dependencies: list[Depends] | None = None) -> typing.Callable: ...
def route_delete(path: str, dependencies: list[Depends] | None = None) -> typing.Callable: ...
def route_query(path: str, body_schema=None, schema=None, experimental: bool = True, dependencies: list[Depends] = None): ...
def route_sse(path: str, dependencies: list[Depends] = None): ...
def route_websocket(path: str, dependencies: list[Depends] = None): ...

class _JustAPIGrpcContext:
    def __init__(self) -> None: ...
    def set_code(self, code) -> None: ...
    def set_details(self, details) -> None: ...
    def abort(self, code, details) -> None: ...

class _JustAPIGrpcMockServer:
    app: Incomplete
    def __init__(self, app) -> None: ...
    def add_generic_rpc_handlers(self, generic_rpc_handlers) -> None: ...
    def add_registered_method_handlers(self, service_name, method_handlers) -> None: ...

class JustAPITestClient:
    def __new__(cls, app, database=None): ...
