import typing
from ._justapi import TokenStreamResponse as TokenStreamResponse
from _typeshed import Incomplete

class Request:
    method: str
    path: str
    scheme: str
    http_version: str
    client: tuple[str, int] | None
    app: Incomplete
    url: URL
    base_url: URL
    scope: dict[str, Incomplete]
    state: State
    user: Incomplete
    auth: Incomplete
    session: Incomplete
    headers: Headers
    query_params: QueryParams
    path_params: dict[str, str]
    cookies: dict[str, str]
    query_string: bytes
    body: bytes
    def json(self) -> Incomplete: ...
    def form(self) -> Incomplete: ...
    def stream(self) -> Incomplete: ...
    def receive(self) -> Incomplete: ...
    def close(self) -> Incomplete: ...
    def is_disconnected(self) -> bool: ...
    def send_push_promise(self, path: str) -> Incomplete: ...
    def url_for(self, name: str, **path_params) -> Incomplete: ...
    def get(self, key: str, default: Incomplete = ...) -> Incomplete: ...
    def __getitem__(self, key: str) -> Incomplete: ...
    def __setitem__(self, key: str, value: Incomplete) -> None: ...
    def __contains__(self, key: str) -> bool: ...

class HTTPConnection:
    method: str
    path: str
    scheme: str
    http_version: str
    client: tuple[str, int] | None
    app: Incomplete
    url: URL
    base_url: URL
    scope: dict[str, Incomplete]
    state: State
    user: Incomplete
    auth: Incomplete
    session: Incomplete
    headers: Headers
    query_params: QueryParams
    path_params: dict[str, str]
    cookies: dict[str, str]
    query_string: bytes
    def receive(self) -> Incomplete: ...
    def url_for(self, name: str, **path_params) -> Incomplete: ...
    def get(self, key: str, default: Incomplete = ...) -> Incomplete: ...
    def __getitem__(self, key: str) -> Incomplete: ...
    def __setitem__(self, key: str, value: Incomplete) -> None: ...
    def __contains__(self, key: str) -> bool: ...

class Headers:
    raw: list[tuple[bytes, bytes]]
    def get(self, key: str, default: Incomplete = ...) -> str | Incomplete: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def mutable(self) -> bool: ...
    def __getitem__(self, key: str) -> str: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> typing.Iterator[str]: ...

class QueryParams:
    def get(self, key: str, default: Incomplete = ...) -> str | Incomplete: ...
    def getlist(self, key: str) -> list[str]: ...
    def multi_items(self) -> list[tuple[str, str]]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def mutable(self) -> bool: ...
    def __getitem__(self, key: str) -> str: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> typing.Iterator[str]: ...

class URL:
    scheme: str
    hostname: str
    host: str
    port: int | None
    path: str
    query: str
    fragment: str
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class State:
    def __getattr__(self, name: str) -> Incomplete: ...
    def __setattr__(self, name: str, value: Incomplete) -> None: ...
    def __getitem__(self, key: str) -> Incomplete: ...
    def __setitem__(self, key: str, value: Incomplete) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...

class RequestStream:
    def __aiter__(self) -> Incomplete: ...
    def __anext__(self) -> Incomplete: ...


class RequestValidationError(Exception):
    errors: Incomplete
    def __init__(self, errors) -> None: ...

class Depends:
    dependency: Incomplete
    use_cache: Incomplete
    def __init__(self, dependency: typing.Callable, use_cache: bool = True) -> None: ...

def adaptive_batch(max_size: int = 32, window_ms: int = 10): ...

class JustAPIApp:
    dependencies: Incomplete
    exception_handlers: Incomplete
    middlewares: Incomplete
    def __init__(self, dependencies: list[Depends] = None) -> None: ...
    def middleware(self, middleware_type: str = 'http'): ...
    def add_exception_handler(self, exc_class, handler) -> None: ...
    def get(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def post(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def put(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def delete(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def patch(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def query(self, path: str, handler=None, body_schema=None, schema=None, experimental: bool = True, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def head(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def options(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def trace(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def url_for(self, name: str, **path_params) -> str: ...
    def frontend(self, path: str, directory: str, html: bool = True, check_dir: bool = True): ...
    def add_plugin(self, plugin) -> None: ...
    def use(self, plugin) -> None: ...
    def set_database(self, db) -> None: ...
    def enable_gateway(self, config_path: str): ...
    def enable_circuit_breaker(self, failure_threshold: int = 5, reset_timeout_ms: int = 10000): ...
    def enable_request_coalescing(self, headers: list[str] = None): ...
    def set_grpc_addr(self, addr: str): ...
    def add_grpc_service(self, servicer, add_func_to_server) -> None: ...
    def include_controller(self, controller_cls) -> None: ...
    def url_for(self, name: str, **path_params) -> str: ...
    def include_router(self, router, prefix: str = '', tags: list[str] = None): ...
    def run(self, addr: str): ...
    def sse(self, path: str, handler=None): ...
    def websocket(self, path: str, handler=None): ...
    def enable_system_routes(self) -> JustAPIApp: ...
    def tool(self, name: str = None, description: str = None, input_schema: Incomplete = None, annotations: Incomplete = None): ...
    def list_tools(self) -> list[dict]: ...
    def call_tool(self, name: str, arguments: dict = None) -> Incomplete: ...
    def create_session(self, data: dict = None) -> str: ...
    def get_session(self, id: str) -> Incomplete: ...
    def set_session(self, id: str, data: dict) -> bool: ...
    def update_session(self, id: str, **fields) -> bool: ...
    def delete_session(self, id: str) -> bool: ...
    def enable_sessions(self, cookie_name: str = ...) -> JustAPIApp: ...
    def stream_json(self, path: str, schema: Incomplete = None, mode: str = ..., handler=None): ...

class APIRouter:
    prefix: Incomplete
    dependencies: Incomplete
    middlewares: Incomplete
    routes: Incomplete
    def __init__(self, prefix: str = '', tags: list[str] = None, responses: dict = None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, callbacks: list[typing.Callable] = None, deprecated: bool = False, include_in_schema: bool = True) -> None: ...
    def get(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def post(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def put(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def patch(self, path: str, handler=None, body_schema=None, schema=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def delete(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def query(self, path: str, handler=None, body_schema=None, schema=None, experimental: bool = True, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def head(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def options(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def trace(self, path: str, handler=None, dependencies: list[Depends] = None, middlewares: list[typing.Callable] = None, tags: list[str] = None, summary: str = None, description: str = None, deprecated: bool = False, status_code: int = None, responses: dict = None, operation_id: str = None, openapi_extra: dict = None, include_in_schema: bool = True, name: str = None): ...
    def url_for(self, name: str, **path_params) -> str: ...
    def frontend(self, path: str, directory: str, html: bool = True, check_dir: bool = True): ...
    def sse(self, path: str, handler=None, dependencies: list[Depends] = None): ...
    def websocket(self, path: str, handler=None, dependencies: list[Depends] = None): ...

class Controller: ...

def controller(path: str, dependencies: list[Depends] = None): ...
def route_get(path: str, dependencies: list[Depends] | None = None) -> typing.Callable: ...
def route_post(path: str, body_schema=None, schema=None, dependencies: list[Depends] | None = None) -> typing.Callable: ...
def route_put(path: str, body_schema=None, schema=None, dependencies: list[Depends] | None = None) -> typing.Callable: ...
def route_patch(path: str, body_schema=None, schema=None, dependencies: list[Depends] | None = None) -> typing.Callable: ...
def route_delete(path: str, dependencies: list[Depends] | None = None) -> typing.Callable: ...
def route_query(path: str, body_schema=None, schema=None, experimental: bool = True, dependencies: list[Depends] = None): ...
def route_sse(path: str, dependencies: list[Depends] = None): ...
def route_websocket(path: str, dependencies: list[Depends] = None): ...

class _JustAPIGrpcContext:
    def __init__(self) -> None: ...
    def set_code(self, code) -> None: ...
    def set_details(self, details) -> None: ...
    def abort(self, code, details) -> None: ...

class _JustAPIGrpcMockServer:
    app: Incomplete
    def __init__(self, app) -> None: ...
    def add_generic_rpc_handlers(self, generic_rpc_handlers) -> None: ...
    def add_registered_method_handlers(self, service_name, method_handlers) -> None: ...

class JustAPITestClient:
    def __new__(cls, app, database=None): ...
