from _typeshed import Incomplete

class BackgroundTasks:
    tasks: Incomplete
    def __init__(self) -> None: ...
    def add_task(self, func, *args, **kwargs) -> None: ...
    def __call__(self) -> None: ...
