from _typeshed import Incomplete
from typing import Any

class Param:
    default: Incomplete
    alias: Incomplete
    def __init__(self, default: Any = ..., alias: str | None = None) -> None: ...

class Path(Param): ...
class Query(Param): ...
class Header(Param): ...
class Cookie(Param): ...
class Body(Param): ...
class File(Param): ...
class Form(Param): ...
