from ._justapi import TokenStreamResponse
"""Type stubs for justapi.responses (auto-generated from runtime introspection)."""
from _typeshed import Incomplete
from typing import Any, Optional, Iterator, Mapping, List, Dict, Callable

class FileResponse(Response):
    def __init__(self, path: Any, headers: Any = ..., media_type: Any = ..., filename: Any = ..., stat_result: Any = ..., content_disposition_type: Any = ..., status_code: Any = ..., background: Any = ...) -> None: ...
    @property
    def charset(self) -> Any: ...
    def delete_cookie(self, name: Any, path: Any = ..., domain: Any = ...) -> Any: ...
    def init_headers(self, headers: Any = ...) -> Any: ...
    @property
    def media_type(self) -> Any: ...
    def render(self, content: Any) -> Any: ...
    def set_cookie(self, name: Any, value: Any = ..., max_age: Any = ..., expires: Any = ..., path: Any = ..., domain: Any = ..., secure: Any = ..., httponly: Any = ..., samesite: Any = ...) -> Any: ...
    def to_dict(self, ) -> Any: ...

class HTMLResponse(Response):
    def __init__(self, content: Any = ..., status_code: Any = ..., headers: Any = ..., media_type: Any = ..., background: Any = ...) -> None: ...
    @property
    def charset(self) -> Any: ...
    def delete_cookie(self, name: Any, path: Any = ..., domain: Any = ...) -> Any: ...
    def init_headers(self, headers: Any = ...) -> Any: ...
    @property
    def media_type(self) -> Any: ...
    def render(self, content: Any) -> Any: ...
    def set_cookie(self, name: Any, value: Any = ..., max_age: Any = ..., expires: Any = ..., path: Any = ..., domain: Any = ..., secure: Any = ..., httponly: Any = ..., samesite: Any = ...) -> Any: ...
    def to_dict(self, ) -> Any: ...

class JSONResponse(Response):
    def __init__(self, content: Any = ..., status_code: Any = ..., headers: Any = ..., media_type: Any = ..., background: Any = ...) -> None: ...
    @property
    def charset(self) -> Any: ...
    def delete_cookie(self, name: Any, path: Any = ..., domain: Any = ...) -> Any: ...
    def init_headers(self, headers: Any = ...) -> Any: ...
    @property
    def media_type(self) -> Any: ...
    def render(self, content: Any) -> Any: ...
    def set_cookie(self, name: Any, value: Any = ..., max_age: Any = ..., expires: Any = ..., path: Any = ..., domain: Any = ..., secure: Any = ..., httponly: Any = ..., samesite: Any = ...) -> Any: ...
    def to_dict(self, ) -> Any: ...

class PlainTextResponse(Response):
    def __init__(self, content: Any = ..., status_code: Any = ..., headers: Any = ..., media_type: Any = ..., background: Any = ...) -> None: ...
    @property
    def charset(self) -> Any: ...
    def delete_cookie(self, name: Any, path: Any = ..., domain: Any = ...) -> Any: ...
    def init_headers(self, headers: Any = ...) -> Any: ...
    @property
    def media_type(self) -> Any: ...
    def render(self, content: Any) -> Any: ...
    def set_cookie(self, name: Any, value: Any = ..., max_age: Any = ..., expires: Any = ..., path: Any = ..., domain: Any = ..., secure: Any = ..., httponly: Any = ..., samesite: Any = ...) -> Any: ...
    def to_dict(self, ) -> Any: ...

class RedirectResponse(Response):
    def __init__(self, url: Any, status_code: Any = ..., headers: Any = ..., background: Any = ...) -> None: ...
    @property
    def charset(self) -> Any: ...
    def delete_cookie(self, name: Any, path: Any = ..., domain: Any = ...) -> Any: ...
    def init_headers(self, headers: Any = ...) -> Any: ...
    @property
    def media_type(self) -> Any: ...
    def render(self, content: Any) -> Any: ...
    def set_cookie(self, name: Any, value: Any = ..., max_age: Any = ..., expires: Any = ..., path: Any = ..., domain: Any = ..., secure: Any = ..., httponly: Any = ..., samesite: Any = ...) -> Any: ...
    def to_dict(self, ) -> Any: ...

class Response(object):
    def __init__(self, content: Any = ..., status_code: Any = ..., headers: Any = ..., media_type: Any = ..., background: Any = ...) -> None: ...
    @property
    def charset(self) -> Any: ...
    def delete_cookie(self, name: Any, path: Any = ..., domain: Any = ...) -> Any: ...
    def init_headers(self, headers: Any = ...) -> Any: ...
    @property
    def media_type(self) -> Any: ...
    def render(self, content: Any) -> Any: ...
    def set_cookie(self, name: Any, value: Any = ..., max_age: Any = ..., expires: Any = ..., path: Any = ..., domain: Any = ..., secure: Any = ..., httponly: Any = ..., samesite: Any = ...) -> Any: ...
    def to_dict(self, ) -> Any: ...

class StreamingResponse(TokenStreamResponse):
    def __init__(self, content: Any, status_code: Any = ..., headers: Any = ..., media_type: Any = ..., background: Any = ...) -> None: ...

