"""Type stubs for justapi.websockets (auto-generated from runtime introspection)."""
from _typeshed import Incomplete
from typing import Any, Optional, Iterator, Mapping, List, Dict, Callable

class WebSocket(object):
    def __init__(self, ws: Any) -> None: ...
    def accept(self, subprotocol: Any = ..., headers: Any = ...) -> Any: ...
    @property
    def app(self) -> Any: ...
    @property
    def application_state(self) -> Any: ...
    @property
    def base_url(self) -> Any: ...
    @property
    def client(self) -> Any: ...
    @property
    def client_state(self) -> Any: ...
    def close(self, code: Any = ..., reason: Any = ...) -> Any: ...
    @property
    def cookies(self) -> Any: ...
    @property
    def headers(self) -> Any: ...
    def iter_bytes(self, ) -> Any: ...
    def iter_json(self, ) -> Any: ...
    def iter_text(self, ) -> Any: ...
    @property
    def path_params(self) -> Any: ...
    @property
    def query_params(self) -> Any: ...
    def receive(self, ) -> Any: ...
    def receive_bytes(self, ) -> Any: ...
    def receive_json(self, mode: Any = ...) -> Any: ...
    def receive_text(self, ) -> Any: ...
    def send(self, message: Any) -> Any: ...
    def send_bytes(self, message: Any) -> Any: ...
    def send_json(self, data: Any, mode: Any = ...) -> Any: ...
    def send_text(self, message: Any) -> Any: ...
    @property
    def state(self) -> Any: ...
    @property
    def subprotocol(self) -> Any: ...
    @property
    def url(self) -> Any: ...
    def url_for(self, name: Any, **path_params: Any) -> Any: ...

class WebSocketDisconnect(Exception):
    def __init__(self, code: Any = ..., reason: Any = ...) -> None: ...
    def add_note(self, *args, **kwargs) -> Any: ...
    @property
    def args(self) -> Any: ...
    def with_traceback(self, *args, **kwargs) -> Any: ...

class WebSocketState(IntEnum):
    CONNECTING: int
    CONNECTED: int
    DISCONNECTED: int
    RESPONSE: int

